name: "Test"

on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v16
      with:
        name: devenv
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Install devenv.sh
      run: nix profile add nixpkgs#devenv

    - name: Build the devenv shell and run pre-commit hooks
      run: devenv test

    - name: Build the f1iptv and f1m3u8 packages
      run: nix build .#f1iptv .#f1m3u8
